name: CI

on:
  push:
    branches: [main]
    
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.103'

      - name: Restore dependencies
        run: dotnet restore TSharp.sln

      - name: Build
        run: dotnet build TSharp.sln --no-restore --configuration Debug

      - name: Test
        run: dotnet test TSharp.sln --no-build --configuration Debug --collect "Code Coverage"
