require "spec"
require "../src/list/list.cr"
require "../src/list/commands/add_at.cr"
require "../src/list/commands/equals.cr"
require "../src/list/commands/take.cr"
require "../src/list/commands/remove_at.cr"
